name: OpenDCS Build and unit tests
on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest,macos-latest,windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '8'
          distribution: adopt
      - uses: actions/setup-python@v3.1.3
        with:
          python-version: "3.8"
# We need a newer version of ant in the linux runner than is setup for some really simple convenience features.
      - name: Compile, test, and bundle jar (linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          mkdir bin
          wget https://dlcdn.apache.org//ant/binaries/apache-ant-1.10.13-bin.tar.gz
          tar -xvzf apache-ant-1.10.13-bin.tar.gz
          export ANT_HOME=`pwd`/apache-ant-1.10.13
          export PATH=$PATH:$ANT_HOME/bin
          ant test stage integration-test -Dno.docs=true
          ant opendcs
      - name: Compile, test, and bundle jar
        if: matrix.platform != 'ubuntu-latest'
        run: |
          ant test stage integration-test -Dno.docs=true
          ant opendcs
#docker-images:
#  runs-on: ubuntu-latest
#  steps:
#   - uses: actions/checkout@v2
#   - name: Set up JDK
#     uses: actions/setup-java@v2
#     with:
#       java-version: '8'
#       distribution: adopt
#   - name: Set up Docker Buildx
#     uses: docker/setup-buildx-action@v2
#   - name: build images
#     run: |
#       docker build --target lrgs -t lrgs:latest-dev .
