name: OpenDCS Build and unit tests
on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest,macos-latest,windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '8'
          distribution: adopt
      - uses: actions/setup-python@v3.1.3
        with:
          python-version: "3.8"
      - name: units tests
        run: |
          ant test -D"no.docs=true"
      - name: integration tests
        # There is an odd issues with the log file name on the windows runner.
        # It does work locally though. Will work on it later.
        if: matrix.platform != 'windows-latest'
        run: |
          ant integration-test -D"no.docs=true"
      - name: Documentation and Create installer jar
        run: |
          ant opendcs
      - name: Upload Test Results
        uses: actions/upload-artifact@v3.1.2
        if: success() || failure()
        with:
          name: test-results-${{matrix.platform}}
          path: |
            build/reports/**
            /tmp/config**
#docker-images:
#  runs-on: ubuntu-latest
#  steps:
#   - uses: actions/checkout@v2
#   - name: Set up JDK
#     uses: actions/setup-java@v2
#     with:
#       java-version: '8'
#       distribution: adopt
#   - name: Set up Docker Buildx
#     uses: docker/setup-buildx-action@v2
#   - name: build images
#     run: |
#       docker build --target lrgs -t lrgs:latest-dev .
